name: Trigger auto deployment for omani-therapist

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/omani-therapist-AutoDeployTrigger-d7dd9c8a-654d-4dcc-a273-82b1a14db3de.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OMANITHERAPIST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OMANITHERAPIST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OMANITHERAPIST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.OMANITHERAPIST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OMANITHERAPIST_REGISTRY_PASSWORD }}
          containerAppName: omani-therapist
          resourceGroup: Arabic_therapist
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


