name: build-and-deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Login to Azure (portal created this secret for you when you wired GitHub)
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build & push image to your ACR
      - uses: azure/container-apps-deploy-action@v2
        with:
          # --- ACR settings (MUST match your registry) ---
          acrName: omanitherapistreg
          imageToBuild: omanitherapistreg.azurecr.io/omani-therapist:${{ github.sha }}
          dockerfilePath: ./Dockerfile

          # --- Container App settings ---
          containerAppName: omani-therapist
          resourceGroup: Arabic_therapist
          containerAppEnvironment: managedEnvironment-Arabictherapist-990c
          targetPort: 8000
          ingress: external
          location: uae-north

          # Optional: env vars here or set them in the Container App UI
          # environmentVariables: |
          #   SECURE_MODE=true
          #   REDACT_LOGS=true
          # secrets: |
          #   AZURE_SPEECH_KEY=${{ secrets.AZURE_SPEECH_KEY }}
          #   OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
